### ISSUE TITLE
Sound doesn't work

### ISSUE THREAD

**Issue by NoltoxGit** [smuddgge/Leaf#108]
`Leaf Version:`
Leaf 5.2.2
**Description of the Bug**
I use staff chat, and i notice the sound doesn't work..
```yml
staff_chat:
  type: "chat"
  enabled: true
  name: "staffchat"
  aliases: [ "sc" ]
  permission: "leaf.staffchat"
  format: "&8[&#e64545&l{server_formatted}&8]&r &6<player>&r &7» &#73a1e6%message%"
  receive_sound: "BLOCK_NOTE_BLOCK_XYLOPHONE"
  sound: "BLOCK_NOTE_BLOCK_XYLOPHONE"
```
