### ISSUE TITLE
Add "delay/cooldown" task

### ISSUE THREAD

**Issue by NoltoxGit** [smuddgge/Leaf#111]
Hello,
Is it possible to add a delay/cooldown task please?
This task will be to put a delay/cooldown on a player's command when they execute it.

For example, with this:
```yml
report:
  type: "report"
  enabled: true
  name: "report"
  aliases: [ "helpop" ]
  # Players with this permission will be able to see all reports.
  see_report: "leaf.report.see"
  see_sound: "none"
  message: "&8[&#e64545&lREPORT &7- &#e64545{server_formatted}&8]&r &6<player>&r &f→ &#e6737a>%message%"
  ```
  
  Add `cooldown: 300 #Time in second`  
  This will prevent the command from being used for 5 minutes.
