### ISSUE TITLE
Require command type option

### ISSUE THREAD

**Issue by smuddgge** [smuddgge/Leaf#30]
**Example**
```yaml
command:
  type: "info"
  enabled: true
  name: "hello"
  message: "world"
  # Require command type option.
  require:
    # Requires this permission if in the servers listed.
    permission_bypass: 
    - ServerName1
    - ServerName2
```

This command type option will allow operators to require different permissions on servers.
An example of this could be stopping players from running `/hub` in the hub. You would do this by requiring permission.

```yaml
require:
  bypass_permission:
  - hub
```

- [ ] Require command type option.

Branching from #26
