### ISSUE TITLE
Info - Missing Character

### ISSUE THREAD

**Issue by CoolDCB** [smuddgge/Leaf#42]
`Leaf Version: 3.3.0`

**Description of the Bug**
- Last character of strings in info type is removed when sending message

**Console Errors**
`none`

**Comment by smuddgge** [comment]
Heyo, thank you for making a bug report. Could you post the commands configuration here so i can recreate the bug? Ill have a look into this some time tomorrow :3

**Comment by CoolDCB** [comment]
For sure! Here is a quick one I just made :)

```
test:
  type: "info"
  enabled: true
  name: "test"
  message:
    - "test"
```
