### ISSUE TITLE
Struggling to detect online players

### ISSUE THREAD

**Issue by CoolDCB** [smuddgge/Leaf#44]
`Leaf Version: 3.3.0`

**Description of the Bug**
When doing `/msg` it often doesn't show a player and when you run the commands says "Player is not online", you also cannot see that person on `/friends online` I am not sure if this is just for single users or for a larger number of players as am just testing with myself and one other person

**Console Errors**
```
none
```

**Comment by smuddgge** [comment]
Is the player you are trying to find have the permission `leaf.vanishable` and on a empty server?
When this happens the plugin is unable to tell if the player is vanished, so it defaults to the config.

```yaml

# The permission used to check if a player is able to vanish.
vanish_permission: "leaf.vanishable"

# Sometimes a vanishable player will be on an empty server.
# Unfortunately we can not check if the player is vanished or not.
# Because of this we assume the player is vanished.
#
# Setting this to true will let other vanishable players see
# vanishable players regardless of the rank.
#
# Defaults to false.
vanishable_can_see_vanishable: false
```
