### ISSUE TITLE
Default StaffChat Formatting Breaks on 1.8

### ISSUE THREAD

**Issue by GronyRalph** [smuddgge/Leaf#59]
`Leaf Version:`
3.7.0

**Description of the Bug**
The formatting of staffchat behaves wrongly on 1.8 and breaks, still sends the message but with "&#c0fce6" before
![image](https://github.com/smuddgge/Leaf/assets/56495047/c8ec2758-133e-445e-acce-19839eb61c55)

**Console Errors**
```
Paste your error here if you get any errors.
```

**Comment by GronyRalph** [comment]
Easily fixable but thought I should let you know

**Comment by smuddgge** [comment]
Thank you for reporting :3 Could you send me the config of where this command is located?

**Comment by smuddgge** [comment]
Could attempt replacing the hex with mini-message hex. For example '<#FFFFFF>'

**Comment by GronyRalph** [comment]
Hey, sorry for the delay, it's commands\commands.yml
haven't really changed much
![image](https://github.com/smuddgge/Leaf/assets/56495047/80ccfca4-3cb0-4b87-a5d0-b6930dc497f3)
yeah, if it works :)

**Comment by smuddgge** [comment]
If you got to placeholders in the leaf folder and find vanish_colour. Try replacing the the hex with <#FFFFFF> instead of &#FFFFFF. Should be something like this:

```yaml
vanish_colour:
  condition: "MATCH:<vanished>"
  options:
    Default: "<#ffffee>"
    true: "<#c0fce6>"
    false: "<#ffffee>"
```

 Let me know if that works :3
