### ISSUE TITLE
Discord command option to only be executed by specific members

### ISSUE THREAD

**Issue by smuddgge** [smuddgge/Leaf#81]
```yaml
discord_ids:
- "548674771013861381"
no_discord_id: "You are not allowed to execute this command"
```
